[package]
name = "shwasi-lang"
version = "0.1.0"
edition = "2021"

[[test]]
name = "integration"
path = "tests/tests.rs"

[dependencies]
thiserror.workspace = true
smol_str = "0.2.0"
dirs = "5.0.1"
duct = "0.13.7"

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
