[package]
name = "shwasi-cmp"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
itertools.workspace = true
reedline.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true
