[package]
name = "shwasi-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
shwasi-parser = { path = "../shwasi-parser" }
paste = "1.0.14"
stacker = "0.1.15"

[lints]
workspace = true
