[package]
name = "shwasi-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
shwasi-parser = { path = "../shwasi-parser" }

[lints]
workspace = true
