[package]
name = "shwasi-engine"
version = "0.1.0"
edition = "2021"

[[test]]
name = "integration"
path = "tests/tests.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.75"
byteorder = "1.5.0"
num_enum = "0.7.0"
thiserror = "1.0.49"
tracing = "0.1.37"
wasm-leb128 = { path = "../wasm-leb128" }
itertools = "0.11.0"
bitflags = "2.4.1"

[dev-dependencies]
insta = "1.34.0"
