[package]
name = "shwasi-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
paste.workspace = true
shwasi-parser = { path = "../shwasi-parser" }
stacker = "0.1.15"

[lints]
workspace = true
