name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: 1
  RUST_LIB_BACKTRACE: 0

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --workspace

  fuzz:
    name: fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - run: cargo install cargo-fuzz
      - run: cargo fuzz run parse --fuzz-dir ./crates/shwasi-parser/fuzz -- -max_total_time=60
      - run: cargo fuzz run module --fuzz-dir ./crates/shwasi-parser/fuzz -- -max_total_time=60
      - run: cargo fuzz run validate --fuzz-dir ./crates/shwasi-parser/fuzz -- -max_total_time=60
      - run: cargo fuzz run lex --fuzz-dir ./crates/shwasi-lang/fuzz -- -max_total_time=60
      - run: cargo fuzz run parse --fuzz-dir ./crates/shwasi-lang/fuzz -- -max_total_time=60

  checkfmt:
    name: checkfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - run: rustup component add rustfmt
      - run: cargo fmt --check --all

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - run: rustup component add clippy
      - run: cargo clippy --workspace --all-targets
